# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semacomp2016', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='title',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='published_date',
        ),
        migrations.AddField(
            model_name='session',
            name='audience_level',
            field=models.IntegerField(choices=[(1, 'Novato'), (2, 'Intermediário'), (3, 'Experiente')], default=1),
        ),
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='session',
            name='session_category',
            field=models.IntegerField(choices=[(1, 'Workshop'), (2, 'Palestra'), (3, 'Competição')], default=1),
        ),
        migrations.AddField(
            model_name='speaker',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='speaker',
            name='image_url',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='institution_url',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsor_level',
            field=models.IntegerField(choices=[(0, ''), (1, 'Prata'), (2, 'Ouro'), (3, 'Diamante')], default=0),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='institution',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='institution',
            field=models.CharField(default='', max_length=200),
        ),
    ]
