# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semacomp2016', '0002_auto_20160725_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='speaker',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='institution',
            new_name='title',
        ),
    ]
